name: Compilación automática

on:
  push:
    branches: [ main, master, push1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Verificar la aplicación
        run: |
          python -c "import flask"
          python -c "import flask_session"
          echo "La aplicación está correctamente configurada"